name "nw-docker"
maintainer "Daniel Nichols"
maintainer_email "dan@nichols.works"
license "mit"
description "Installs/Configures nw-docker"
long_description "Installs/Configures nw-docker"
version "0.1.0"

depends "apt"
depends "chef-apt-docker"
depends "docker"
depends "cloudcli"
depends "tar"

supports "ubuntu"
